language: python
cache: pip

before_install: pip install --upgrade pip
install: pip install tox codecov
script: tox

jobs:
  include:
    - python: '3.4'
      env: TOXENV=py34-cover
    - python: '3.5'
      env: TOXENV=py35-cover
    - python: '3.6'
      env: TOXENV=py36-cover
    - python: '3.7'
      env: TOXENV=py37-cover
    - python: '3.7'
      env: TOXENV=lint

    - stage: release
      if: tag IS present
      deploy:
        provider: pypi
        user: jamieh
        password: todo
        distributions: sdist bdist_wheel
        on: {tags: true}

      before_install: skip
      install: skip
      script: skip
